//
//  MovieDetailWorker.swift
//  SpoilerAlert
//
//  Created by Guillermo Costa on 5/18/19.
//  Copyright (c) 2019 Usuario. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MovieDetailWorker
{
  func doSomeWork()
  {
  }
}
